"""added column author

Revision ID: 4d18fa44da48
Revises: 1fb3a2ff123f
Create Date: 2025-05-12 03:34:51.755689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d18fa44da48"
down_revision: Union[str, None] = "1fb3a2ff123f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("author", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "author")
    # ### end Alembic commands ###
